
variable "ip" {
  type    = string
  default = "172.168.1.201"
}

variable "password" {
  type    = string
  default = "cluster"
}

variable "username" {
  type    = string
  default = "root@pam"
}
# The "legacy_isotime" function has been provided for backwards compatability, but we recommend switching to the timestamp and formatdate functions.

source "proxmox" "autogenerated_1" {
  boot_command = ["<up><tab> ip=dhcp inst.cmdline inst.ks=http://{{ .HTTPIP }}:{{ .HTTPPort }}/ks/centos-7-proxmox.cfg<enter>"]
  boot_wait    = "10s"
  disks {
    disk_size         = "5G"
    storage_pool      = "local-lvm"
    storage_pool_type = "lvm"
    type              = "scsi"
  }
  http_bind_address        = "${var.ip}"
  http_directory           = "."
  insecure_skip_tls_verify = true
  iso_file                 = "local:iso/CentOS-7-x86_64-Minimal-2003.iso"
  network_adapters {
    bridge = "vmbr0"
  }
  node                 = "pve"
  password             = "${var.password}"
  proxmox_url          = "https://172.16.1.62:8006/api2/json"
  ssh_password         = "vagrant"
  ssh_timeout          = "15m"
  ssh_username         = "vagrant"
  template_description = "CentOS-7, generated on ${legacy_isotime("2020-012-29T20:04:05Z")}"
  template_name        = "CentOS-7"
  unmount_iso          = true
  username             = "${var.username}"
}

build {
  sources = ["source.proxmox.autogenerated_1"]

}
