
variable "guest_additions" {
  type    = string
  default = "disable"
}

variable "iso_name" {
  type    = string
  default = "CentOS-Stream-8-x86_64-20210126-boot.iso"
}

variable "iso_url" {
  type    = string
  default = "http://bay.uchicago.edu/centos/8-stream/isos/x86_64/CentOS-Stream-8-x86_64-20210902-boot.iso"
}

variable "kickstart" {
  type    = string
  default = "ks/centos-8-stream.cfg"
}

variable "proxy" {
  type    = string
  default = "${env("http_proxy")}"
}

source "virtualbox-iso" "autogenerated_1" {
  boot_command            = ["<tab> text ks=http://{{ .HTTPIP }}:{{ .HTTPPort }}/ks/centos-8-stream.cfg<enter>", "<wait10><wait10><wait10>", "<wait10><wait10><wait10>", "<wait10><wait10><wait10>", "<wait10><wait10><wait10>", "<wait10><wait10><wait10>", "<wait10><wait10><wait10>", "<wait10><wait10><wait10>", "<wait10><wait10><wait10>", "<wait10><wait10><wait10>", "<wait10><wait10><wait10>", "<wait10><wait10><wait10>", "<wait10><wait10><wait10>"]
  boot_wait               = "10s"
  disk_size               = 32768
  guest_additions_mode    = "${var.guest_additions}"
  guest_additions_path    = "VBoxGuestAdditions_{{ .Version }}.iso"
  guest_os_type           = "RedHat_64"
  hard_drive_interface    = "sata"
  headless                = false
  http_directory          = "http"
  iso_checksum            = "sha256:7f5c9eaf0b8364db195baa1200849c8175f5c4d2f2cb24a654c53390a906d02e"
  iso_urls                = ["${var.iso_url}"]
  shutdown_command        = "echo 'vagrant'| sudo -S /sbin/poweroff"
  ssh_password            = "vagrant"
  ssh_port                = 22
  ssh_timeout             = "30m"
  ssh_username            = "vagrant"
  vboxmanage              = [["modifyvm", "{{ .Name }}", "--memory", "2048"], ["modifyvm", "{{ .Name }}", "--cpus", "2"]]
  virtualbox_version_file = ".vbox_version"
}

build {
  description = "Build base CentOS 8 x86_64"

  sources = ["source.virtualbox-iso.autogenerated_1"]

  provisioner "shell" {
    environment_vars = ["http_proxy=${var.proxy}", "guest_additions_mode=${var.guest_additions}"]
    scripts          = ["../scripts/post_install_vagrant-centos-8.sh"]
  }

  post-processor "vagrant" {
    output               = "${var.box_name}.box"
    vagrantfile_template = "Vagrantfile"
  }
}
